# Generated by Django 5.0.1 on 2024-02-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_alter_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
