# Generated by Django 5.0.1 on 2024-02-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_documents_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
